### ISSUE TITLE
Update runtime to 3.34

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.transmissionbt.Transmission#24]

**Comment by codingepaduli** [comment]
The file com.transmissionbt.Transmission.yaml is still on version 3.32.
"runtime": "org.gnome.Platform",
"runtime-version": "3.32"

Can you reopen the bug or add a description about the missing update?
Thank you.

**Comment by wjt** [comment]
I see no pressing reason to update this.

**Comment by codingepaduli** [comment]
It's one of the few programs still using the 3.32. 
Updating it, many flatpak user can safely remove org.gnome.Platform 3.32, freeing 1Gb of space..

**Comment by wjt** [comment]
```
$ flatpak remote-ls flathub --system --app --columns=application,runtime | grep org.gnome.Platform/x86_64/3.32 | wc -l
56
$ flatpak remote-ls flathub --system --app --columns=application,runtime | wc -l
722
```

I guess it's a matter of perspective, but 56 is a big few :-)

I'm very aware of the problem of proliferating runtimes – having to ship a dozen runtimes reduces the number of apps we can fit pre-installed on an Endless OS system – but I just don't think org.gnome.Platform//3.32 is the problem here. If updating the runtime could be accompanied by some other user-facing improvement, that's a different matter.

I'll reopen the ticket to reflect the state of affairs.
