### ISSUE TITLE
update GNOME runtime to 3.38

### ISSUE THREAD

**Issue by eszlari** [flathub/com.transmissionbt.Transmission#29]

**Comment by wjt** [comment]
I believe the 3.36 runtime (which is currently in use) will be supported until the GNOME 40 release in March 2021. I don't think there is any need to rebuild the app against 3.38 before that – unless there is some other reason to update it, in which case, let's do it.

**Comment by eszlari** [comment]
* user have to download fewer runtimes
* 3.38 is based on freedesktop runtime 20.08

**Comment by codingepaduli** [comment]
Desktop users choose flatpak and flathub against "apt-get install" because they expect to have, all the times, the latest version of the software (app and runtime). With the choice to not update to 3.38, the whole flathub "ecosystem" will be slow down from this point of view.    

Anyway, Thank you for your great work.

**Comment by wjt** [comment]
Fixed in #33
